# Dynamic synthesis of generated specification
dynamicvalidation: clean dynamicSynthesis.cpp
	g++ -std=c++14 -pthread dynamicSynthesis.cpp -o dynamicSynthesis && ./dynamicSynthesis
clean:
	rm -f dynamicSynthesis